apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognigraph.fullname" . }}
  labels:
    {{- include "cognigraph.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "cognigraph.serverSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognigraph.fullname" . }}-headless
  labels:
    {{- include "cognigraph.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    {{- include "cognigraph.serverSelectorLabels" . | nindent 4 }}
